name: deploy_github_pages
on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build_commit_and_publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
      id-token: write
    steps:
      - name: Setup Python
        uses: actions/setup-python@v5.0.0
        with:
          python-version: "3.11"

      - name: Checkout sources
        uses: actions/checkout@v4.1.1
        with:
          path: main
          fetch-depth: 0

      - name: Checkout github_docs
        uses: actions/checkout@v4.1.1
        with:
          ssh-key: ${{ secrets.RSA_PRIVATE_KEY }}
          ref: github_docs
          path: github_docs

      - name: Install sphinx
        shell: bash
        run: |
          pip install -r main/doc/requirements.txt

      - name: Build docs
        shell: bash
        run: |
          rm -rf github_docs/build
          sphinx-build -b dirhtml main/doc github_docs/build

      - name: Commit changes
        uses: EndBug/add-and-commit@v9.1.3
        with:
          cwd: github_docs
          commit: "--amend"
          push: "--force"
          default_author: github_actions
          message: "[bot] Build github pages"

      - name: Setup Github Pages
        uses: actions/configure-pages@v5

      - name: Upload Github Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "github_docs/build"

      - name: Build Github Pages
        uses: actions/deploy-pages@v4
